/*
 * resnet_pico.c
 * =======================
 * Minimal ResNet-8 inference engine for the Raspberry Pi Pico (RP2040).
 *
 * Architecture:
 *   Input (32x32x1 greyscale)
 *     -> Conv0 (3x3, 1->16 ch) + BN + ReLU
 *     -> ResBlock 1 (16->16, identity shortcut)
 *     -> ResBlock 2 (16->32, stride-2 downsample + projection shortcut)
 *     -> ResBlock 3 (32->32, identity shortcut)
 *     -> Global Average Pool (16x16x32 -> 32)
 *     -> FC (32 -> 10 logits)
 *     -> argmax -> predicted digit (0-9)
 *
 * All arithmetic uses Q8.8 fixed-point (int16_t) so no FPU is required.
 * The RP2040 Cortex-M0+ has no hardware floating-point unit; using float
 * would require software emulation and run ~10x slower.
 *
 * Weights are generated by train_and_export.py (PyTorch -> Q8.8 int16)
 * and stored in weights_mnist.h as const arrays in flash.
 */

#include <stdint.h>
#include <string.h>
#include <stdio.h>

#ifdef PICO_BUILD
#include "pico/stdlib.h"
#include "hardware/watchdog.h"  /* watchdog_enable() used by 'reboot' command */
#endif

#include "weights_mnist.h"   /* trained Q8.8 weight arrays for all layers */

/* =========================================================================
 * Configuration — must match the values used when weights were exported
 * ========================================================================= */
#define INPUT_H       32     /* image height in pixels (MNIST 28x28 padded to 32) */
#define INPUT_W       32     /* image width in pixels */
#define INPUT_C       1      /* input channels: 1 = greyscale, 3 = RGB */
#define NUM_CLASSES   10     /* output classes: digits 0-9 */

/* =========================================================================
 * Fixed-point arithmetic — Q8.8 format
 *
 * Q8.8 means: 1 sign bit + 7 integer bits + 8 fractional bits (16-bit total)
 *   value 256  = 1.0
 *   value 128  = 0.5
 *   value -256 = -1.0
 *
 * To multiply two Q8.8 values we need a 32-bit accumulator (acc_t) because
 * multiplying two 16-bit values can produce a 32-bit result. After summing
 * we right-shift by FP_SHIFT (8) to bring the result back to Q8.8 scale.
 * ========================================================================= */
#define FP_SHIFT   8
#define FP_ONE     (1 << FP_SHIFT)          /* 256 — represents 1.0 in Q8.8 */
#define FP_ROUND   (1 << (FP_SHIFT - 1))    /* 128 — used for rounding before shift */

typedef int16_t  fp_t;   /* Q8.8 fixed-point value (one activation or weight) */
typedef int32_t  acc_t;  /* wider accumulator used during multiply-accumulate */

/*
 * fp_clamp — saturate a 32-bit accumulator to the int16 range.
 *
 * After accumulating many products the sum can exceed 16-bit range.
 * We clamp it to [-32768, 32767] before storing back as fp_t.
 * Without clamping, the cast to int16_t would silently wrap and produce
 * wildly wrong activations.
 */
static inline fp_t fp_clamp(acc_t x) {
    if (x >  32767) return  32767;
    if (x < -32768) return -32768;
    return (fp_t)x;
}

/*
 * fp_mul — multiply two Q8.8 values and return a Q8.8 result.
 *
 * The product of two Q8.8 values is a Q16.16 value (32-bit).
 * Right-shifting by FP_SHIFT (8) converts it back to Q8.8.
 * FP_ROUND (128) is added before the shift for correct rounding
 * (equivalent to adding 0.5 before truncation).
 *
 * Note: fp_mul is defined but not called directly in the main inference
 * path — the inner loop of conv2d performs the same operation inline
 * for performance.
 */
static inline fp_t fp_mul(fp_t a, fp_t b) {
    return (fp_t)(((acc_t)a * b + FP_ROUND) >> FP_SHIFT);
}

/*
 * fp_relu — Rectified Linear Unit activation in fixed-point.
 *
 * ReLU(x) = max(0, x). Clamps all negative activations to zero,
 * introducing non-linearity between layers. Without ReLU, stacking
 * linear conv layers would be equivalent to a single linear transform.
 * This function is branch-heavy but the Cortex-M0+ handles it fine at
 * this scale.
 */
static inline fp_t fp_relu(fp_t x) { return x > 0 ? x : 0; }

/* =========================================================================
 * Tensor index helpers (channels-last layout: H x W x C)
 *
 * Channels-last means values for all channels at position (h,w) are
 * contiguous in memory. This makes the innermost channel loop in conv2d
 * access sequential memory addresses — cache-friendly on the M0+ tiny cache.
 * ========================================================================= */
#define IDX3(h, w, c, W, C)     ((h)*(W)*(C) + (w)*(C) + (c))
#define IDX4(n,h,w,c,H,W,C)     ((n)*(H)*(W)*(C)+(h)*(W)*(C)+(w)*(C)+(c))

/* =========================================================================
 * Layer size defines — match the exported weight array dimensions
 * ========================================================================= */
#define L0_OUT_C  16    /* conv0 output channels */
#define L1_C      16    /* ResBlock 1 channels (in = out = 16) */
#define L2_IN_C   16    /* ResBlock 2 input channels */
#define L2_OUT_C  32    /* ResBlock 2 output channels (doubles after stride-2) */
#define L3_C      32    /* ResBlock 3 channels (in = out = 32) */

/* =========================================================================
 * Scratch buffers — reused across all layers to avoid dynamic allocation.
 *
 * buf_a and buf_b are ping-ponged: one holds the current layer's input,
 * the other receives the output. They are sized for the largest tensor
 * that passes through them: 32x32x32 = 32768 fp_t values = 65536 bytes.
 * After ResBlock 2 downsamples to 16x16, only half of each buffer is used.
 *
 * Static globals avoid repeated stack allocation and heap fragmentation,
 * both of which are problematic on the Pico's 264 KB SRAM.
 * ========================================================================= */
static fp_t buf_a[INPUT_H * INPUT_W * L2_OUT_C]; /* primary working buffer */
static fp_t buf_b[INPUT_H * INPUT_W * L2_OUT_C]; /* secondary/scratch buffer */

/* =========================================================================
 * conv2d — 2D convolution (the core compute primitive)
 *
 * Slides every filter (kernel) across the input feature map and computes
 * dot products to produce the output feature map. This is the most
 * computationally expensive function in the network.
 *
 * Parameters:
 *   in       - input tensor, shape [H][W][in_c], channels-last
 *   H, W     - input spatial dimensions
 *   in_c     - number of input channels
 *   out      - output tensor, shape [OH][OW][out_c], caller-allocated
 *   OH, OW   - output spatial dimensions (= H/stride if no padding)
 *   out_c    - number of output channels (= number of filters)
 *   weights  - flat array of shape [kH][kW][in_c][out_c]
 *   bias     - per-output-channel bias, shape [out_c]
 *   kH, kW   - kernel (filter) height and width (typically 3x3 or 1x1)
 *   stride   - step size when sliding the kernel (1 = full res, 2 = halve)
 *   pad      - zero-padding added around the input border (1 for "same" with 3x3)
 *
 * Inner loop order (oh, ow, oc, kh, kw, ic):
 *   - Iterates over every output position (oh, ow)
 *   - For each output channel oc, accumulates the dot product over the
 *     3x3 kernel window and all input channels ic
 *   - The accumulator is 32-bit (acc_t) to prevent overflow during
 *     the multiply-accumulate; right-shifted back to Q8.8 at the end
 *
 * Weight layout [kH][kW][in_c][out_c] (channels-last):
 *   The innermost dimension is out_c, so for a fixed kernel position
 *   (kh, kw) and input channel ic, all output-channel weights are
 *   contiguous. This makes the oc loop sequential in memory.
 * ========================================================================= */
static void conv2d(
    const fp_t *in,  int H, int W, int in_c,
          fp_t *out, int OH, int OW, int out_c,
    const fp_t *weights,
    const fp_t *bias,
    int kH, int kW, int stride, int pad)
{
    printf("[DEB] conv2d start\n");
    /* Zero the output buffer — bias is added per-channel in the loop below */
    memset(out, 0, (size_t)(OH * OW * out_c) * sizeof(fp_t));

    for (int oh = 0; oh < OH; oh++) {
        for (int ow = 0; ow < OW; ow++) {
            for (int oc = 0; oc < out_c; oc++) {

                /*
                 * Start the accumulator with the bias for this output channel.
                 * The bias is a real-world float baked to Q8.8 at export time,
                 * so we pre-shift it left by FP_SHIFT to match the scale of
                 * the accumulating products (which are Q16.16 before >> 8).
                 */
                acc_t sum = (acc_t)bias[oc] << FP_SHIFT;

                /* Slide the kH x kW kernel over the input */
                for (int kh = 0; kh < kH; kh++) {
                    int ih = oh * stride - pad + kh; /* corresponding input row */
                    if (ih < 0 || ih >= H) continue; /* skip rows outside input (zero-padding) */

                    for (int kw = 0; kw < kW; kw++) {
                        int iw = ow * stride - pad + kw; /* corresponding input col */
                        if (iw < 0 || iw >= W) continue; /* skip cols outside input */

                        for (int ic = 0; ic < in_c; ic++) {
                            fp_t iv = in[IDX3(ih, iw, ic, W, in_c)];   /* input value */
                            fp_t wv = weights[
                                ((kh * kW + kw) * in_c + ic) * out_c + oc]; /* weight */

                            /*
                             * Multiply-accumulate: both iv and wv are Q8.8,
                             * so iv*wv is Q16.16 (32-bit). We accumulate many
                             * of these before right-shifting at the end.
                             */
                            sum += (acc_t)iv * wv;
                        }
                    }
                }

                /*
                 * Convert accumulated Q16.16 sum back to Q8.8:
                 *   - Add FP_ROUND (128) for rounding (equivalent to +0.5 before truncation)
                 *   - Right-shift by FP_SHIFT (8) to remove the extra fractional bits
                 *   - Clamp to int16 range to prevent overflow wrap-around
                 */
                out[IDX3(oh, ow, oc, OW, out_c)] =
                    fp_clamp((sum + FP_ROUND) >> FP_SHIFT);
            }
        }
    }

    printf("[DEB] conv2d ends\n");
}

/* =========================================================================
 * batchnorm_relu — apply batch normalisation then ReLU activation.
 *
 * At training time, BatchNorm normalises each channel's activations to
 * zero mean and unit variance, then scales/shifts with learned parameters
 * gamma and beta. At inference time this simplifies to a per-channel
 * linear transform: y = scale * x + shift.
 *
 * In this implementation, BatchNorm is FOLDED into the preceding conv's
 * weights and biases during export (train_and_export.py). So at runtime
 * scale = 1 and shift = 0 for all channels (identity transform via _ones16
 * and _zeros16). The function is kept for correctness if non-identity
 * BN parameters are ever needed.
 *
 * After BN, ReLU clamps all negative values to 0, adding the non-linearity
 * that lets the network learn complex decision boundaries.
 *
 * Parameters:
 *   x           - feature map, shape [numel_per_c][C], modified in-place
 *   numel_per_c - number of spatial positions (H*W)
 *   C           - number of channels
 *   scale       - per-channel BN scale (gamma/sqrt(var+eps)), Q8.8
 *   shift       - per-channel BN shift (beta - mean*scale), Q8.8
 * ========================================================================= */
static void batchnorm_relu(fp_t *x, int numel_per_c, int C,
                            const fp_t *scale, const fp_t *shift)
{
    for (int i = 0; i < numel_per_c; i++) {
        for (int c = 0; c < C; c++) {
            acc_t v = (acc_t)x[i * C + c];

            /*
             * Apply BN linear transform: v = scale[c] * v + shift[c]
             * scale[c] is Q8.8, so multiplying by it gives Q16.16;
             * right-shifting by FP_SHIFT converts back to Q8.8, then
             * add the shift (also Q8.8).
             */
            v = ((v * scale[c]) >> FP_SHIFT) + shift[c];

            /* Apply ReLU in-place */
            x[i * C + c] = fp_relu(fp_clamp(v));
        }
    }
}

/*
 * _ones16 / _zeros16 — identity batch-norm parameters.
 *
 * scale = 1.0 (FP_ONE = 256 in Q8.8) and shift = 0.0 produce a no-op BN,
 * because BN is already folded into the conv weights at export time.
 * Sized for the widest layer (L2_OUT_C = 32 channels).
 */
static fp_t _ones16[L2_OUT_C];
static fp_t _zeros16[L2_OUT_C];

/*
 * init_bn_identity — initialise the identity BN buffers.
 *
 * Called once at the start of each inference pass. Fills _ones16 with
 * FP_ONE (= 1.0 in Q8.8) and _zeros16 with 0, so batchnorm_relu() is
 * effectively a pass-through + ReLU.
 */
static void init_bn_identity(void) {
    for (int i = 0; i < L2_OUT_C; i++) {
        _ones16[i]  = FP_ONE;
        _zeros16[i] = 0;
    }
}

/* =========================================================================
 * resblock — standard residual block (identity shortcut).
 *
 * Implements the core ResNet building block:
 *
 *   input x
 *     |------------ skip (identity) ------------.
 *     v                                          |
 *   Conv A (3x3) + BN + ReLU                    |
 *     v                                          |
 *   Conv B (3x3) + BN  (NO ReLU yet)            |
 *     v                                          |
 *   [add] <--------------------------------------'
 *     v
 *   ReLU
 *     v
 *   output (same shape as input)
 *
 * The skip connection passes the original input directly to the addition.
 * If Conv A and Conv B learn to output zero, the block behaves as an
 * identity function — the network can "skip" learning in this block
 * if it isn't beneficial. This also provides a direct gradient path
 * during backpropagation, preventing vanishing gradients.
 *
 * Used for ResBlock 1 (16ch, 32x32) and ResBlock 3 (32ch, 16x16).
 * Input and output shapes are identical so no projection is needed.
 *
 * Parameters:
 *   x    - input tensor [H][W][C], overwritten with output in-place
 *   tmp  - scratch buffer, same size as x (used for Conv A output)
 *   H, W - spatial dimensions
 *   C    - number of channels (in == out for identity blocks)
 *   wa   - Conv A weights [3][3][C][C]
 *   ba   - Conv A biases [C]
 *   wb   - Conv B weights [3][3][C][C]
 *   bb   - Conv B biases [C]
 * ========================================================================= */
static void resblock(fp_t *x, fp_t *tmp,
                     int H, int W, int C,
                     const fp_t *wa, const fp_t *ba,
                     const fp_t *wb, const fp_t *bb)
{

    printf("\r\n[RB] START (H=%d W=%d C=%d)\r\n", H, W, C);
    /*
     * Conv A: x -> tmp
     * Applies 3x3 conv with stride=1, padding=1 (output same spatial size).
     * Followed immediately by BN (identity) + ReLU.
     */
    printf("[RB] Conv A START (3x3 same)\r\n");
    conv2d(x, H, W, C, tmp, H, W, C, wa, ba, 3, 3, 1, 1);
    batchnorm_relu(tmp, H * W, C, _ones16, _zeros16);
    printf("[RB] Conv A END\r\n");

    /*
     * Conv B: tmp -> x_new (using buf_b as scratch)
     * No ReLU here — the skip connection must be added first before
     * activating. This matches the original ResNet paper design.
     */
    printf("[RB] Conv B START (3x3 same)\r\n");
    fp_t *x_new = buf_b;
    conv2d(tmp, H, W, C, x_new, H, W, C, wb, bb, 3, 3, 1, 1);
    printf("[RB] Conv B END\r\n");

    /*
     * Add skip connection and apply ReLU.
     * x still holds the original block input (the skip).
     * x_new holds Conv B's output.
     * We add them element-wise and ReLU in-place into x.
     */
    printf("[RB] Adding skip connection + ReLU\r\n");
    for (int i = 0; i < H * W * C; i++)
        x[i] = fp_relu(fp_clamp((acc_t)x_new[i] + x[i]));

    printf("[RB] END\r\n");
}

/* =========================================================================
 * resblock_ds — downsampling residual block (projection shortcut).
 *
 * Like resblock() but the block simultaneously:
 *   1. Doubles the number of channels (in_c -> out_c, e.g. 16->32)
 *   2. Halves the spatial dimensions using stride=2 (e.g. 32x32 -> 16x16)
 *
 * Because the input and output shapes differ, the skip connection cannot
 * be a plain identity — the tensors have incompatible shapes. A 1x1
 * "projection" convolution with stride=2 transforms the shortcut to
 * match the output shape before the addition.
 *
 *   input x [H][W][in_c]
 *     |--- 1x1 proj conv (stride=2) ---> shortcut [OH][OW][out_c]
 *     |
 *     v
 *   Conv A (3x3, stride=2) + BN + ReLU  -> tmp [OH][OW][out_c]
 *     v
 *   Conv B (3x3, stride=1) + BN         -> main2 [OH][OW][out_c]
 *     v
 *   [add shortcut] -> ReLU
 *     v
 *   output [OH][OW][out_c]   (written back over x in buf_a)
 *
 * Used only for ResBlock 2 in this network (16ch->32ch, 32x32->16x16).
 *
 * Parameters:
 *   x       - input tensor [H][W][in_c]; on return holds output [OH][OW][out_c]
 *   tmp     - scratch, large enough for OH*OW*out_c + OH*OW*out_c
 *             (split: first half = Conv A output, second half = shortcut)
 *   H, W    - input spatial dimensions
 *   in_c    - input channels
 *   out_c   - output channels (must be > in_c for this to be useful)
 *   wa/ba   - Conv A weights/biases [3][3][in_c][out_c]
 *   wb/bb   - Conv B weights/biases [3][3][out_c][out_c]
 *   wp/bp   - projection weights/biases [1][1][in_c][out_c]
 * ========================================================================= */
static void resblock_ds(
    fp_t *x,
    fp_t *tmp,
    int H, int W, int in_c, int out_c,
    const fp_t *wa, const fp_t *ba,
    const fp_t *wb, const fp_t *bb,
    const fp_t *wp, const fp_t *bp)
{

    int OH = H / 2, OW = W / 2; /* output spatial size after stride-2 */

    printf("\r\n[RB_DS] START (H=%d W=%d in_c=%d -> out_c=%d)\r\n",
           H, W, in_c, out_c);
    /*
     * Projection shortcut: 1x1 conv with stride=2.
     * Transforms input from [H][W][in_c] -> [OH][OW][out_c].
     * Stored in the second half of tmp to avoid clobbering Conv A's output.
     * pad=0 because 1x1 kernels don't need padding.
     */

    printf("[RB_DS] Projection START (1x1 stride=2)\r\n");

    fp_t *shortcut = tmp + OH * OW * out_c;
    conv2d(x, H, W, in_c, shortcut, OH, OW, out_c, wp, bp, 1, 1, 2, 0);
    
    printf("[RB_DS] Projection END (output %dx%dx%d)\r\n",
           OH, OW, out_c);

    /*
     * Conv A: stride=2, so spatial dims halve (H->OH, W->OW).
     * Channels expand from in_c to out_c.
     * Output stored in the first half of tmp.
     */
    printf("[RB_DS] Conv A START (3x3 stride=2)\r\n");

    conv2d(x, H, W, in_c, tmp, OH, OW, out_c, wa, ba, 3, 3, 2, 1);
    batchnorm_relu(tmp, OH * OW, out_c, _ones16, _zeros16);

    printf("[RB_DS] Conv A END\r\n");

    /*
     * Conv B: stays at reduced spatial size, same channel count.
     * Uses buf_b as scratch (main2) — no ReLU yet.
     */
    printf("[RB_DS] Conv B START (3x3 stride=1)\r\n");

    fp_t *main2 = buf_b;
    conv2d(tmp, OH, OW, out_c, main2, OH, OW, out_c, wb, bb, 3, 3, 1, 1);
    
    printf("[RB_DS] Conv B END\r\n");
    /*
     * Add projection shortcut to Conv B output, then ReLU.
     * Result is written back to x (which is buf_a), overwriting the
     * now-consumed input. buf_a now holds the [OH][OW][out_c] output.
     */
    printf("[RB_DS] Adding projection shortcut + ReLU\r\n");

    for (int i = 0; i < OH * OW * out_c; i++)
        x[i] = fp_relu(fp_clamp((acc_t)main2[i] + shortcut[i]));

    printf("[RB_DS] END (output %dx%dx%d)\r\n", OH, OW, out_c);
}

/* =========================================================================
 * global_avg_pool — collapse spatial dimensions by averaging.
 *
 * For each channel c, compute the mean activation across all H*W spatial
 * positions. Output is a 1D vector of length C, one value per channel.
 *
 * This replaces the traditional "flatten + huge FC" approach. Instead of
 * passing 16*16*32 = 8192 values into the FC layer (which would need
 * 8192*10 = 81920 weights), we average each channel's spatial map to a
 * single scalar, giving just 32 values -> 32*10 = 320 FC weights.
 *
 * The 256x compression (8192->32) also makes the classifier translation-
 * invariant: a digit drawn anywhere in the image produces the same pooled
 * vector, improving generalisation.
 *
 * Parameters:
 *   x    - input tensor [H][W][C], channels-last
 *   H, W - spatial dimensions
 *   C    - number of channels
 *   out  - output vector [C], caller-allocated
 * ========================================================================= */
static void global_avg_pool(const fp_t *x, int H, int W, int C, fp_t *out)
{
    int n = H * W; /* total spatial positions to average over */
    for (int c = 0; c < C; c++) {
        acc_t sum = 0;
        /*
         * Sum all H*W activations for channel c.
         * Channels-last layout: channel c at position i is at x[i*C + c].
         */
        for (int i = 0; i < n; i++)
            sum += x[i * C + c];

        /*
         * Divide by H*W to get the mean.
         * Note: when H=W=16, n=256=2^8, so this is equivalent to a right-
         * shift by 8 — the compiler may optimise the division accordingly.
         * fp_clamp guards against the (unlikely) case of sum overflowing int16.
         */
        out[c] = fp_clamp(sum / n);
    }
}

/* =========================================================================
 * fc — fully-connected (linear) layer.
 *
 * Computes out[o] = sum_i(in[i] * W[i][o]) + b[o] for each output o.
 * This is a matrix-vector multiply: out = W^T * in + b.
 *
 * In this network, fc maps the 32-value global-pooled vector to 10 logits,
 * one per digit class. The logit with the highest value is the prediction.
 *
 * Parameters:
 *   in    - input vector [in_c], Q8.8
 *   in_c  - number of input features (32 = L3_C after global avg pool)
 *   out   - output logit vector [out_c], caller-allocated
 *   out_c - number of output classes (10 = NUM_CLASSES)
 *   W     - weight matrix, flat [in_c][out_c], Q8.8
 *   b     - bias vector [out_c], Q8.8
 * ========================================================================= */
static void fc(const fp_t *in, int in_c,
                     fp_t *out, int out_c,
               const fp_t *W, const fp_t *b)
{
    for (int o = 0; o < out_c; o++) {
        /*
         * Initialise accumulator with bias, pre-shifted to Q16.16 scale
         * so it aligns with the Q16.16 products accumulated below.
         */
        acc_t sum = (acc_t)b[o] << FP_SHIFT;

        /* Dot product: sum += in[i] * W[i][o] for all input features */
        for (int i = 0; i < in_c; i++)
            sum += (acc_t)in[i] * W[i * out_c + o];

        /* Convert Q16.16 accumulator back to Q8.8 with rounding and clamping */
        out[o] = fp_clamp((sum + FP_ROUND) >> FP_SHIFT);
    }
}

/* =========================================================================
 * argmax — find the index of the largest value in an array.
 *
 * Used to pick the predicted class from the 10 output logits.
 * No softmax is needed at inference time — we only care which logit is
 * highest, not the actual probability values.
 *
 * Parameters:
 *   x - array of fp_t values (logits)
 *   n - number of elements
 *
 * Returns:
 *   index of the maximum element (0-9 for MNIST)
 * ========================================================================= */
static int argmax(const fp_t *x, int n) {
    int best = 0;
    for (int i = 1; i < n; i++)
        if (x[i] > x[best]) best = i;
    return best;
}


/* =========================================================================
 * softmax_display — convert logits to display-friendly scores.
 *
 * NOTE: This function is currently a stub — it does not compute true
 * softmax probabilities. Full softmax requires expf() which pulls in
 * float arithmetic. For display purposes the raw logit values (converted
 * to float by dividing by 256) are sufficient to show relative confidence.
 *
 * A proper softmax would be:
 *   probs[i] = exp(logits[i] - max_logit) / sum(exp(logits[j] - max_logit))
 *
 * Parameters:
 *   logits - Q8.8 logit array [n]
 *   probs  - output float array [n], filled with raw logit floats
 *   n      - number of classes
 * ========================================================================= */
static void softmax_display(const fp_t *logits, float *probs, int n)
{
    /* Find max logit for numerical stability (used if full softmax added) */
    float fmax = (float)logits[0] / 256.0f;
    for (int i = 1; i < n; i++) {
        float v = (float)logits[i] / 256.0f;
        if (v > fmax) fmax = v;
    }

    /* Placeholder: fill probs with 1.0 (softmax not yet implemented) */
    float sum = 0.0f;
    for (int i = 0; i < n; i++) {
        float v = (float)logits[i] / 256.0f - fmax;
        probs[i] = 1.0f;
        sum += probs[i];
        (void)v; /* suppress unused-variable warning */
    }

    /* For now just convert raw logits to float — good enough for bar chart */
    for (int i = 0; i < n; i++)
        probs[i] = (float)logits[i] / 256.0f;
}

/* =========================================================================
 * print_results — display inference results as a bar chart over USB serial.
 *
 * Prints all 10 class scores as ASCII bar charts with '#' and '-' characters,
 * then announces the predicted digit. Example output:
 *
 *   ========= ResNet MNIST Result =========
 *   0: [--------------------]   score=-1.23
 *   7: [####################] * score= 2.14
 *   =======================================
 *   >>> Predicted digit: 7 <<<
 *
 * The bar length is proportional to the logit value, normalised between
 * the min and max logit so the winner always fills the full bar width.
 *
 * Parameters:
 *   logits    - Q8.8 logit array [NUM_CLASSES]
 *   predicted - index of the predicted class (output of argmax)
 * ========================================================================= */
static void print_results(const fp_t *logits, int predicted)
{
    /* Find the range of logit values to normalise bar lengths */
    fp_t lmin = logits[0], lmax = logits[0];
    for (int i = 1; i < NUM_CLASSES; i++) {
        if (logits[i] < lmin) lmin = logits[i];
        if (logits[i] > lmax) lmax = logits[i];
    }
    fp_t range = lmax - lmin;
    if (range == 0) range = 1; /* avoid division by zero if all logits equal */

#define BAR_WIDTH 20

    printf("\r\n========= ResNet MNIST Result =========\r\n");
    for (int i = 0; i < NUM_CLASSES; i++) {

        /* Bar length: linearly scale logit into [0, BAR_WIDTH] */
        int bar_len = (int)(((long)(logits[i] - lmin) * BAR_WIDTH) / range);
        char bar[BAR_WIDTH + 1];
        for (int b = 0; b < BAR_WIDTH; b++)
            bar[b] = (b < bar_len) ? '#' : '-';
        bar[BAR_WIDTH] = '\0';

        /*
         * Convert Q8.8 logit to a decimal string without printf floats.
         * integer_part = upper 8 bits (whole number portion)
         * frac_part    = lower 8 bits scaled to 0-99 (two decimal places)
         */
        int integer_part = logits[i] >> 8;
        int frac_part    = ((logits[i] & 0xFF) * 100) >> 8;
        if (frac_part < 0) frac_part = -frac_part;

        /* '*' marks the predicted class, ' ' for all others */
        printf("  %d: [%s] %c score=%d.%02d\r\n",
               i, bar,
               (i == predicted) ? '*' : ' ',
               integer_part, frac_part);
    }
    printf("=======================================\r\n");
    printf("  >>> Predicted digit: %d <<<\r\n", predicted);
    printf("=======================================\r\n\r\n");
}

/*
 * g_logits — global buffer to hold the 10 output logits from the last
 * inference run. Declared globally so print_results() can read them
 * after resnet_infer_full() returns.
 */
static fp_t g_logits[NUM_CLASSES];

/* =========================================================================
 * resnet_infer_full — full inference pass that also stores logits.
 *
 * Identical to resnet_infer() but writes the raw logits into the global
 * g_logits[] buffer before returning, so the caller can pass them to
 * print_results() for the bar chart display.
 *
 * Parameters:
 *   image_u8 - raw greyscale image, INPUT_H * INPUT_W * INPUT_C bytes
 *
 * Returns:
 *   Predicted class index 0-9
 *
 * Side effects:
 *   Fills g_logits[NUM_CLASSES] with the 10 output logit values.
 * ========================================================================= */
int resnet_infer_full(const uint8_t *image_u8)
{
    init_bn_identity();

    /* Normalise: uint8 [0,255] -> Q8.8 roughly [-1.0, 1.0] */
    for (int i = 0; i < INPUT_H * INPUT_W * INPUT_C; i++)
        buf_a[i] = (fp_t)((int)image_u8[i] - 128) * 2;

    /* Conv0 + BN + ReLU: 1ch -> 16ch, 32x32 */
    conv2d(buf_a, INPUT_H, INPUT_W, INPUT_C,
           buf_b, INPUT_H, INPUT_W, L0_OUT_C,
           (const fp_t *)w_conv0, b_conv0, 3, 3, 1, 1);
    batchnorm_relu(buf_b, INPUT_H * INPUT_W, L0_OUT_C, _ones16, _zeros16);
    memcpy(buf_a, buf_b, INPUT_H * INPUT_W * L0_OUT_C * sizeof(fp_t));

    /* ResBlock 1: 16ch, 32x32, identity shortcut */
    resblock(buf_a, buf_b, INPUT_H, INPUT_W, L1_C,
             (const fp_t *)w_rb1_a, b_rb1_a,
             (const fp_t *)w_rb1_b, b_rb1_b);

    /* ResBlock 2: 16->32ch, 32x32->16x16, projection shortcut */
    resblock_ds(buf_a, buf_b, INPUT_H, INPUT_W, L2_IN_C, L2_OUT_C,
                (const fp_t *)w_rb2_a,    b_rb2_a,
                (const fp_t *)w_rb2_b,    b_rb2_b,
                (const fp_t *)w_rb2_proj, b_rb2_proj);

    /* ResBlock 3: 32ch, 16x16, identity shortcut */
    resblock(buf_a, buf_b, INPUT_H / 2, INPUT_W / 2, L3_C,
             (const fp_t *)w_rb3_a, b_rb3_a,
             (const fp_t *)w_rb3_b, b_rb3_b);

    /* Global average pool: 16x16x32 -> 32 */
    fp_t gap[L3_C];
    global_avg_pool(buf_a, INPUT_H / 2, INPUT_W / 2, L3_C, gap);

    /* FC: 32 -> 10 logits, stored in global g_logits for print_results() */
    fc(gap, L3_C, g_logits, NUM_CLASSES, (const fp_t *)w_fc, b_fc);

    return argmax(g_logits, NUM_CLASSES);
}

/* =========================================================================
 * cmd_read_line — read a line of text from USB serial into buf.
 *
 * Blocks until the user presses Enter. Handles backspace so the user
 * can correct typos. Characters are echoed back so the terminal shows
 * what is being typed. The returned string is null-terminated and does
 * NOT include the newline character.
 *
 * Parameters:
 *   buf     - destination buffer
 *   max_len - maximum characters to accept (including null terminator)
 * ========================================================================= */
static void cmd_read_line(char *buf, int max_len)
{
    int pos = 0;
    while (1) {
        /*
         * getchar_timeout_us(0) is non-blocking — returns PICO_ERROR_TIMEOUT
         * if no character is waiting. We spin here; the LED blink in the
         * outer loop keeps the board feeling alive while we wait.
         */
        int c = getchar_timeout_us(10000); /* 10 ms timeout per poll */

        if (c == PICO_ERROR_TIMEOUT) continue; /* nothing yet, keep waiting */

        if (c == '\r' || c == '\n') {
            /* Enter pressed — terminate string and return */
            buf[pos] = '\0';
            printf("\r\n");
            return;
        }

        if ((c == 127 || c == '\b') && pos > 0) {
            /* Backspace — erase last character from terminal and buffer */
            pos--;
            printf("\b \b"); /* move back, overwrite with space, move back */
            continue;
        }

        if (c >= 32 && c < 127 && pos < max_len - 1) {
            /* Printable character — store and echo it */
            buf[pos++] = (char)c;
            printf("%c", c); /* echo so user sees what they typed */
        }
    }
}

/* =========================================================================
 * cmd_print_help — print the list of available commands.
 * ========================================================================= */
static void cmd_print_help(void)
{
    printf("\r\n  Commands:\r\n");
    printf("    start   — run inference on the built-in test image\r\n");
    printf("    info    — show network architecture summary\r\n");
    printf("    help    — show this message\r\n");
    printf("    reboot  — reset the Pico\r\n");
    printf("\r\n");
}

/* =========================================================================
 * cmd_print_info — print a summary of the ResNet architecture and memory.
 * ========================================================================= */
static void cmd_print_info(void)
{
    printf("\r\n");
    printf("  +---------------------------------+\r\n");
    printf("  |  ResNet-8 MNIST — Pico Summary  |\r\n");
    printf("  +---------------------------------+\r\n");
    printf("  Input        : 32 x 32 x 1 (greyscale)\r\n");
    printf("  Conv0        : 3x3, 1->16 ch, 144 weights\r\n");
    printf("  ResBlock 1   : 3x3, 16->16 ch, identity skip\r\n");
    printf("  ResBlock 2   : 3x3, 16->32 ch, stride-2 + proj\r\n");
    printf("  ResBlock 3   : 3x3, 32->32 ch, identity skip\r\n");
    printf("  GlobalAvgPool: 16x16x32 -> 32\r\n");
    printf("  FC           : 32 -> 10 logits\r\n");
    printf("  +---------------------------------+\r\n");
    printf("  Total params : ~26,506\r\n");
    printf("  Weight size  : ~130 KB (flash)\r\n");
    printf("  Scratch SRAM : ~131 KB (buf_a + buf_b)\r\n");
    printf("  Precision    : Q8.8 fixed-point (int16)\r\n");
    printf("  Expected acc : ~98%% on MNIST test set\r\n");
    printf("  +---------------------------------+\r\n");
    printf("\r\n");
}

/* =========================================================================
 * main — interactive console entry point.
 *
 * Flow:
 *   1. Wait for USB serial to connect (up to 5 seconds).
 *   2. Print a welcome banner.
 *   3. Enter an infinite command loop:
 *        - Show a prompt  >
 *        - Read a line from the terminal
 *        - Dispatch the command:
 *            start  -> run inference + print results
 *            info   -> print architecture summary
 *            help   -> print command list
 *            reboot -> watchdog reset
 *        - Unknown commands get a friendly error message.
 *   4. LED blinks at 1 Hz throughout as a heartbeat.
 *
 * Connect with:
 *   Linux/macOS : screen /dev/ttyACM0 115200
 *   Windows     : PuTTY -> Serial -> COMx -> 115200
 * ========================================================================= */
int main(void)
{
#ifdef PICO_BUILD
    stdio_init_all(); /* initialise USB serial (and UART) */

    /*
     * Wait up to 5 seconds for the host to open the serial port.
     * Each iteration is 100 ms, so 50 iterations = 5 seconds.
     * We break early as soon as stdio_usb_connected() returns true.
     */
    for (int i = 0; i < 50; i++) {
        if (stdio_usb_connected()) break;
        sleep_ms(100);
    }

    /* Set up the onboard LED (GPIO 25) for heartbeat blink */
    const uint LED_PIN = 25;
    gpio_init(LED_PIN);
    gpio_set_dir(LED_PIN, GPIO_OUT);
#endif

    /* ------------------------------------------------------------------ */
    /* Welcome banner                                                       */
    /* ------------------------------------------------------------------ */
    printf("\r\n");
    printf("  ========================================\r\n");
    printf("  ResNet MNIST — Raspberry Pi Pico\r\n");
    printf("  ========================================\r\n");
    printf("  Q8.8 fixed-point ResNet-8 inference\r\n");
    printf("  Type  help  to see available commands.\r\n");
    printf("  ========================================\r\n");
    printf("\r\n");

    /*
     * Test image used by the 'start' command.
     * Currently all-zero (blank). Replace with real MNIST pixel data:
     *   - 32x32 pixels, 1 byte per pixel, row-major, greyscale 0-255
     *   - If source is 28x28 MNIST, pad 2 pixels of zeros on each side
     */
    static const uint8_t test_image[INPUT_H * INPUT_W * INPUT_C] = {
        0   /* placeholder — replace with real image bytes */
    };

    /* ------------------------------------------------------------------ */
    /* Command loop — runs forever                                          */
    /* ------------------------------------------------------------------ */
    char cmd_buf[64]; /* buffer for one line of user input */

    while (1) {

#ifdef PICO_BUILD
        /* Heartbeat: toggle LED every half-second while waiting for input */
        gpio_put(LED_PIN, 1);
#endif

        /* Print prompt and read a command */
        printf("> ");
        cmd_read_line(cmd_buf, sizeof(cmd_buf));

#ifdef PICO_BUILD
        gpio_put(LED_PIN, 0);
#endif

        /* ---- Dispatch ------------------------------------------------ */

        if (strcmp(cmd_buf, "start") == 0) {
            /*
             * start — run the full inference pipeline on test_image[].
             * Prints progress markers so you can see which layer is running,
             * then shows the bar chart of all 10 class scores.
             */

            int predicted = resnet_infer_full(test_image);
            print_results(g_logits, predicted);

        } else if (strcmp(cmd_buf, "info") == 0) {
            /*
             * info — print a table of the network architecture and
             * memory usage so you can understand what is running.
             */
            cmd_print_info();

        } else if (strcmp(cmd_buf, "help") == 0 || strcmp(cmd_buf, "?") == 0) {
            /*
             * help / ? — list all available commands.
             */
            cmd_print_help();

        } else if (strcmp(cmd_buf, "reboot") == 0) {
            /*
             * reboot — trigger a watchdog reset to restart the Pico.
             * Useful after flashing new weights without unplugging.
             */
            printf("  Rebooting...\r\n");
#ifdef PICO_BUILD
            watchdog_enable(1, 1); /* 1 ms timeout -> instant reset */
            while (1);             /* wait for watchdog to fire */
#else
            printf("  (reboot not available on host build)\r\n");
#endif

        } else if (cmd_buf[0] == '\0') {
            /* Empty line — just show a new prompt, no error */
            continue;

        } else {
            /* Unknown command */
            printf("  Unknown command: '%s'\r\n", cmd_buf);
            printf("  Type  help  for available commands.\r\n");
            printf("\r\n");
        }
    }

    return 0; /* unreachable but satisfies the compiler */
}
